spring:
  datasource:
    url: jdbc:postgresql://dpg-cojpt0md3nmc73c07ihg-a.oregon-postgres.render.com:5432/buy_sell_db_bwis
    username: buysellshop
    password: yTWWK7lZp4hGr3hXGSgz10KocZBJ0e5o
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
