spring:
  datasource:
    url: jdbc:postgresql://dpg-cojpt0md3nmc73c07ihg-a.oregon-postgres.render.com/buy_sell_db_bwis
    username: buysellshop
    password: TtyPOixawbxm7WC26dQacp8SQ2TqtDLO
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Виправлення: вказуємо платформу бази даних, а не ім'я бази даних
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
